type Program {
    """
    Below field is convenient but also causes N+1 problem.
    Because if you query this field it will perform an extra data-fetch using
    data needed from the current fetch, usually the ID.
    """
    ProgramEnrichments: [ProgramEnrichment]
}

"""
Description of a sponsor of a program
"""
type ProgramSponsor {
    """
    URL to sponsor
    """
    url: String
    """
    Name of sponsor
    """
    name: String
    """
    Logo of sponsor
    """
    logo: String
}

"""
Program enrichment from Sanity CMS.
"""
type ProgramEnrichment {
    """
    Program color
    """
    color: String
    """
    Program sponsors
    """
    sponsors: [ProgramSponsor]
}

type Query {
    """
    Get the program enrichment from Sanity
    """
    programEnrichments(programId: String!): [ProgramEnrichment]
}
