name: Build
on: [push, pull_request]
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x]
        experimental: [false]
        include:
        - node: 15.x
          experimental: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js (NPMJS) ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm test
      env:
        CLOUDSEARCH_SEARCH_URL: ${{ secrets.CLOUDSEARCH_SEARCH_URL }}
        OMNY_ORGID: ${{ secrets.OMNY_ORGID }}
        SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
        SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
        SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
    - name: Build
      run: npm run build
      env:
        CLOUDSEARCH_SEARCH_URL: ${{ secrets.CLOUDSEARCH_SEARCH_URL }}
        OMNY_ORGID: ${{ secrets.OMNY_ORGID }}
        SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
        SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
        SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
    - name: Code coverage reporting
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./js-coverage/lcov.info
      continue-on-error: true